In [1]:
import cv2

In [2]:
def name_map(x):
    if x=="sachin":
        return 0
    if x=="obama":
        return 1
    if x=="messi":
        return 2

In [3]:
def get_name(x):
    if x==0:
        return "sachin"
    if x==1:
        return 'obama'
    if x==2:
        return "messi"

In [4]:
def detect_face(img):
    gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    face_cascade=cv2.CascadeClassifier(r"D:\DL Projects\face_recognition\haarcascade_frontalface_default.xml")
    face=face_cascade.detectMultiScale(gray,minNeighbors=10)
    if len(face)==0:
        return None,None
    x,y,w,h=face[0]   #frst elemt lle value x,y,w,h llot pokm
    return gray[x:x+w,y:y+h],face[0]

In [5]:
# img=cv2.imread(r"WhatsApp Image 2024-01-02 at 14.17.21_e8072a82.jpg")
# detect_face(img)

In [6]:
import os

In [7]:
def prepare_training_data(data_folder):
    dirs=os.listdir(data_folder)
    print(dirs)
    faces=[]
    labels=[]
    for dir_name in dirs :  #dir=messi
        sub_dir=data_folder+'/'+dir_name
        # print(sub_dir)
        images=os.listdir(sub_dir)
        print(images)
        for img in images:
            imgpath=sub_dir+'/'+img
            # print(imgpath)
            image=cv2.imread(imgpath)
            cv2.imshow("training image",image)
            cv2.waitKey(500)
            # detect
            face,rect=detect_face(image)
            if face is not None:
                faces.append(face)
                labels.append(name_map(dir_name))
                print(labels)
                
            
    cv2.waitKey(1)
    cv2.destroyAllWindows()
    return faces,labels


In [8]:

prepare_training_data(r"D:\DL Projects\face_recognition\DB")




['messi', 'obama', 'sachin']
['01.jpg', '02.jpg', '03.jpg', '04.jpg', '05.jpg', '06.jpg', '07.jpg', '08.jpg', '09.jpg', '10.jpg']
[2]
[2, 2]
[2, 2, 2]
[2, 2, 2, 2]
[2, 2, 2, 2, 2]
[2, 2, 2, 2, 2, 2]
[2, 2, 2, 2, 2, 2, 2]
[2, 2, 2, 2, 2, 2, 2, 2]
[2, 2, 2, 2, 2, 2, 2, 2, 2]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
['01.jpg', '02.jpg', '03.jpg', '04.jpg', '05.jpg', '06.jpg', '07.jpg', '08.jpg', '09.jpg', '10.jpg']
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
['01.jpg', '02.jpg', '03.jpg', '04.jpg', '05.jpg', '06.jpg', '07.jpg', '08.jpg', '09.jpg', '10.jpg']
[2, 2, 2, 2, 2, 2,

([array([[ 14,  12,  12, ..., 151, 151, 151],
         [ 33,  37,  37, ..., 151, 151, 151],
         [ 20,  20,  22, ..., 151, 151, 151],
         ...,
         [ 29,  33,  38, ...,  88,  88,  88],
         [ 31,  33,  46, ..., 102, 102, 102],
         [ 44,  29,  40, ..., 107, 107, 107]], dtype=uint8),
  array([[247, 247, 247, ..., 153, 157, 174],
         [247, 247, 247, ..., 151, 158, 176],
         [247, 247, 247, ..., 155, 162, 180],
         ...,
         [221, 201, 224, ...,  39,  43,  42],
         [216, 235, 222, ...,  35,  34,  34],
         [230, 227, 232, ...,  32,  33,  32]], dtype=uint8),
  array([[247, 247, 247, ..., 117, 116, 114],
         [247, 247, 247, ...,  91,  83,  77],
         [247, 247, 247, ...,  68,  55,  47],
         ...,
         [247, 247, 248, ..., 179, 177, 174],
         [247, 247, 244, ..., 178, 175, 171],
         [247, 247, 241, ..., 177, 173, 169]], dtype=uint8),
  array([[ 38,  19,  24, ..., 255, 255, 255],
         [ 13,  22,  28, ..., 255, 255,

In [9]:
faces,labels=prepare_training_data(r"D:\DL Projects\face_recognition\DB")
print(labels)

['messi', 'obama', 'sachin']
['01.jpg', '02.jpg', '03.jpg', '04.jpg', '05.jpg', '06.jpg', '07.jpg', '08.jpg', '09.jpg', '10.jpg']
[2]
[2, 2]
[2, 2, 2]
[2, 2, 2, 2]
[2, 2, 2, 2, 2]
[2, 2, 2, 2, 2, 2]
[2, 2, 2, 2, 2, 2, 2]
[2, 2, 2, 2, 2, 2, 2, 2]
[2, 2, 2, 2, 2, 2, 2, 2, 2]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
['01.jpg', '02.jpg', '03.jpg', '04.jpg', '05.jpg', '06.jpg', '07.jpg', '08.jpg', '09.jpg', '10.jpg']
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
['01.jpg', '02.jpg', '03.jpg', '04.jpg', '05.jpg', '06.jpg', '07.jpg', '08.jpg', '09.jpg', '10.jpg']
[2, 2, 2, 2, 2, 2,

In [10]:
len(labels)

28

In [11]:
recognizer=cv2.face.LBPHFaceRecognizer_create()
recognizer

< cv2.face.LBPHFaceRecognizer 00000259FF0C3230>

In [12]:
# converting in t numpy
import numpy as np

In [13]:
recognizer.train(faces,np.array(labels))

In [14]:
# predictions
def draw_rectangle(img,rect):
    (x,y,w,h)=rect
    cv2.rectangle(img,(x,y),(x+w,y+h),(0,0,0),2)
    


In [15]:
def write_text(img,text,x,y):
    cv2.putText(img,text,(x,y),cv2.FONT_HERSHEY_COMPLEX,1,(0,0,255),2)
    # a person face and the name of the persons face

In [16]:
def predict_new(test_img):
    img=test_img
    face,rect=detect_face(test_img)
    label=recognizer.predict(face)
    # print(label)
    label_text=get_name(label[0])
    print(label_text)
    draw_rectangle(img,rect)
    write_text(img,label_text,rect[0],rect[1])
    return (img)


In [17]:
test_img=cv2.imread(r"D:\DL Projects\face_recognition\WhatsApp Image 2024-01-02 at 14.17.20_f50790d4.jpg")
predicted=predict_new(test_img)
cv2.imshow("IMAGE",predicted)
cv2.waitKey()
cv2.destroyAllWindows()

messi
